### ISSUE TITLE
Two crashed in x64 totalcmd.

### ISSUE THREAD

**Issue by loved3d** [alexx2000/ArchView#1]
when switch tags to"about","comment", it crashed.
when read files larger than 4G, it reports ErrorSeekFile.

**Comment by alexx2000** [comment]
First I hope fixed, check with version 0.9.2.2.
Which archive type you viewed in second case?

**Comment by loved3d** [comment]
Thank you very much. The first case has been fixed.
Second the archive I tested was a 8G and 16G size tar.gz file. It still there.

**Comment by alexx2000** [comment]
Fixed.
