### ISSUE TITLE
Unable to read rar5 archive

### ISSUE THREAD

**Issue by loved3d** [alexx2000/ArchView#2]
The config  in archview is 
```
[Libraries]
Rar=%COMMANDER_PATH%\unrar.dll
```
the unrar.dll version is 5.80.0.

The archview plugin unable to read rar archive with type rar5.

**Comment by alexx2000** [comment]
Plugin read archive using internal parser. Library unrar.dll used for read archive comment only. This internal parser does not support rar5. Needs to add rar5 support via unrar.dll.
