### ISSUE TITLE
Number confusion when reading large 7z files

### ISSUE THREAD

**Issue by loved3d** [alexx2000/ArchView#3]
The config of archview is:

```
[WCXPluginsTC]
7ZIP=%COMMANDER_PATH%\PLUGINS\WCX\Total7Zip\Total7Zip.wcx64

[WCXExtensions]
OnlyExtensions=1
7Zip=7z 7zip exe
```

The following are screenshots with two plugins read the same file Downloads.7z (6.86GB).

![Annotation 2020-10-12 103135](https://user-images.githubusercontent.com/32627372/95699098-303e5e00-0c76-11eb-86f6-b15a9c3a4ee9.png)

![Annotation 2020-10-12 103251](https://user-images.githubusercontent.com/32627372/95699151-4fd58680-0c76-11eb-96fb-e05eb5bc2c05.png)

**Comment by alexx2000** [comment]
I guess fixed.
