### ISSUE TITLE
7zip - мало информации о архиве.

### ISSUE THREAD

**Issue by g0blin-NN** [alexx2000/ArchView#4]
пардон если я на русском. русский плохо знаю, а английский вообще нет. :)
я посмотрел в ArchView.ini вы задействовали библиотеку UNRAR64.DLL для rar-архивов и оно работает. так почему бы не задействовать для 7zip библиотеку TC7Z64.DLL, а не плагин? а если ее еще подменить на библиотеку [отсюда](https://github.com/mcmilk/7-Zip-zstd#codec-plugin-for-total-commander)  добавится еще информация. ведь 7zip разные бывают.

спасибо за плагин. извиняйте что побеспокоил.

**Comment by alexx2000** [comment]
Добавил поддержку 7-Zip через TC7Z.DLL/TC7Z64.DLL.

**Comment by g0blin-NN** [comment]
спасибо! но есть проблема. на архивах вот с таким именем `(1993-04-14) Любовь Успенская - Любимый.7z` все падает. даже тотал закрывается. если его переименовать например `arch.7z` показывает нормально.

**Comment by alexx2000** [comment]
Не могу воспроизвести. Переименовал архив в "(1993-04-14) Любовь Успенская - Любимый.7z", открывается.

**Comment by g0blin-NN** [comment]
значит это у меня глюки. буду искать. еще раз спасибо.
